name: testing

on:
  push:

  pull_request:

  # everyday at 3 am UTC
  #  schedule:
  #   - cron:  '0 3 * * *'

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
        exclude:
          - os: windows-latest
            python-version: 3.8

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade setuptools wheel pip twine numpy
        pip install -e .[dev]

    - name: Install Solcore Linux and MacOS
      if: matrix.os != 'windows-latest'
      run: pip install -e .

    - name: Install Solcore Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip install -e .
      shell: powershell

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests
